name:                chapter5
version:             0.1.0.0
github:              "samueller/chapter5"
license:             BSD3
author:              "Scott Mueller"
maintainer:          "scott@sup.ai"
copyright:           "Copyright (c) 2019 Scott Mueller"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/samueller/chapter5#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  chapter5-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter5

tests:
  chapter5-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter5
    - QuickCheck
    - hspec
